version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/go/src/app:/go/src/app
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/react:/react
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true # https://teratail.com/questions/249875
